#ifndef __HSPSDK_PACKAGE_INFO_H__
#define __HSPSDK_PACKAGE_INFO_H__

#define HSPSDK_SUPPORTS_CORE
#define HSPSDK_SUPPORTS_UI
#define HSPSDK_SUPPORTS_PROMOTION
#define HSPSDK_SUPPORTS_PAYMENT
#define HSPSDK_SUPPORTS_ITEMDELIVERY

#endif // __HSPSDK_PACKAGE_INFO_H__
