#pragma once

enum HSPLoginTypeX
{
#if CC_TARGET_PLATFORM == CC_PLATFORM_ANDROID 
	HSPLoginTypeUNKNOWN,
  HSPLoginTypeGUEST,
  HSPLoginTypeGSQAURE,
  HSPLoginTypeFACEBOOK,
  HSPLoginTypeKAKAO,
  HSPLoginTypeTOAST,
  HSPLoginTypeGOOGLE,
  HSPLoginTypeNAVER
#elif CC_TARGET_PLATFORM == CC_PLATFORM_IOS
	HSPLoginTypeUNKNOWN,
	HSPLoginTypeGUEST,
	HSPLoginTypeGSQAURE,
	HSPLoginTypeFACEBOOK,
	HSPLoginTypeKAKAO,
	HSPLoginTypeTOAST,
	HSPLoginTypeGOOGLE,
	HSPLoginTypeNAVER
//	HSP_LOGIN_TYPE_UNKNOWN = 0,
//	HSP_LOGIN_TYPE_GUEST,
//	HSP_LOGIN_TYPE_GSQUARE,
//	HSP_LOGIN_TYPE_FACEBOOK,
//	HSP_LOGIN_TYPE_KAKAO,
//	HSP_LOGIN_TYPE_CREATINGACCOUNT,
//	HSP_LOGIN_TYPE_TOAST,
//	HSP_LOGIN_TYPE_PAYCO,
//	HSP_LOGIN_TYPE_GAMECENTER,
#endif
};

enum class HSPMapping
{
#if CC_TARGET_PLATFORM == CC_PLATFORM_ANDROID
	
	kID,
	kHANGAME,
	kTOAST,
	kBAND,
	kFACEBOOK= 4,
	kGOOGLE,
	kNAVER,
	kTWITTER
	
	
#elif CC_TARGET_PLATFORM == CC_PLATFORM_IOS
	kHANGAME = 0,	/**< Hangame mapping type. */
	kTOAST,			/**< Toast mapping type. */
	kFACEBOOK,       /**< Facebook mapping type. */
	kTWITTER,        /**< Twitter mapping type. */
	kGAMECENTER,		/**< Game Center mapping type. */
	kNAVER			/**< Naver mapping type. */
#endif
};

// 안드로이드는 실제 oauth 하기위해 쓰고
// ios 는 이거 할거다? 하면서 물어보기 위해 쓰는 듯.
enum class HSPLogin
{
#if CC_TARGET_PLATFORM == CC_PLATFORM_ANDROID
	TWITTER,
	MIXI,
	FACEBOOK,
	GOOGLE,
	HANGAME,
	NAVER,
	LINE,
	KAKAO,
	GREE,
	HANGAME_EX,
	POKETROKET,
	HANGAMEJP,
	HANGAMEJP_EMAIL,
	NEID,
	GUEST,
	GSQUARE,
	BAND
	
#elif CC_TARGET_PLATFORM == CC_PLATFORM_IOS
	TWITTER,
	MIXI,
	FACEBOOK,
	GAMECENTER,
	HANGAME,
	NAVER,
	LINE,
	KAKAO,
	GREE,
	HANGAME_EX,
	POKETROKET,
	HANGAMEJP,
	HANGAMEJP_EMAIL,
	NEID,
	GUEST,
	GSQUARE,
	BAND
#endif
};