#pragma once

enum HSPLoginTypeX
{
#if CC_TARGET_PLATFORM == CC_PLATFORM_ANDROID 
	HSPLoginTypeUNKNOWN,
  HSPLoginTypeGUEST,
  HSPLoginTypeGSQAURE,
  HSPLoginTypeFACEBOOK,
  HSPLoginTypeKAKAO,
  HSPLoginTypeCREATING_ACCOUNT,
  HSPLoginTypeTOAST,
  HSPLoginTypePAYCO,
  HSPLoginTypeGOOGLE 
#elif CC_TARGET_PLATFORM == CC_PLATFORM_IOS
	HSPLoginTypeUNKNOWN,
  HSPLoginTypeGUEST,
  HSPLoginTypeGSQAURE,
  HSPLoginTypeFACEBOOK,
  HSPLoginTypeKAKAO,
  HSPLoginTypeCREATING_ACCOUNT,
  HSPLoginTypeTOAST,
  HSPLoginTypePAYCO,
  HSPLoginTypeGOOGLE
	
	
//	HSP_LOGIN_TYPE_UNKNOWN = 0,
//	HSP_LOGIN_TYPE_GUEST,
//	HSP_LOGIN_TYPE_GSQUARE,
//	HSP_LOGIN_TYPE_FACEBOOK,
//	HSP_LOGIN_TYPE_KAKAO,
//	HSP_LOGIN_TYPE_CREATINGACCOUNT,
//	HSP_LOGIN_TYPE_TOAST,
//	HSP_LOGIN_TYPE_PAYCO,
//	HSP_LOGIN_TYPE_GAMECENTER,
#endif
};

enum class HSPMapping
{
#if CC_TARGET_PLATFORM == CC_PLATFORM_ANDROID
	kID,
	kHANGAME,
	kEMAIL,
	kBAND,
	kFACEBOOK,
	kGOOGLE,
	kTWITTER
#elif CC_TARGET_PLATFORM == CC_PLATFORM_IOS
	kHANGAME,
	kEMAIL,
	kFACEBOOK,
	kTWITTER,
	kGAMECENTER
#endif
};

enum class HSPLogin
{
#if CC_TARGET_PLATFORM == CC_PLATFORM_ANDROID
	TWITTER,
	MIXI,
	FACEBOOK,
	YAHOO,
	GOOGLE,
	HANGAME,
	NAVER,
	LINE,
	KAKAO,
	GREE,
	HANGAME_EX,
	POKETROKET,
	HANGAMEJP,
	HANGAMEJP_EMAIL,
	EMAIL,
	NEID,
	PAYCO,
	GUEST,
	GSQUARE,
	BAND
#elif CC_TARGET_PLATFORM == CC_PLATFORM_IOS
	TWITTER,
	MIXI,
	FACEBOOK,
	YAHOO,
	GOOGLE,
	HANGAME,
	NAVER,
	LINE,
	KAKAO,
	GREE,
	HANGAME_EX,
	GSQUARE,
	POKETROKET,
	NEID,
	GUEST,
	WEIBO,
	GAMECENTER	
#endif
};