var ccb_resources = [
    {type:'image', src:"ccbResources/ccbDefaultImages.png"},
    {type:'ccbi', src:"boss1.ccbi"},
    {type:'ccbi', src:"MainScene.ccbi"},
    {type:'image', src:"ccbResources/ccbParticleSmoke.png"},
    {type:'image', src:"siler1_rubylight.png"},
    {type:'image', src:"ccbResources/ccbParticleFire.png"},
    {type:'image', src:"gold1.png"},
    {type:'image', src:"siler1_rubyback.png"},
    {type:'image', src:"ccbResources/ccbParticleStars.png"},
    {type:'image', src:"siler1_ruby.png"},
    {type:'image', src:"siler1_arrow.png"},
    {type:'ccbi', src:"boss2.ccbi"},
    {type:'plist', src:"ccbResources/ccbDefaultImages.plist"},
    {type:'image', src:"ccbResources/ccbParticleSnow.png"},
];
